// Generated by scripts/update-abis.sh from https://github.com/MakinaHQ/makina-core.git@eb9a2fea6cac9f88783f9c769927ed7e5c2b7fd5
// Source: src/libraries/Errors.sol:Errors. Do not edit.
export const coreErrorsAbi = [
  {
    "inputs": [],
    "name": "AccountingToken",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ActiveUpdatePending",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "AlreadyAccountingAgent",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "AlreadyBaseToken",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "AlreadyDisabled",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "AlreadyEnabled",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "AlreadyPositionToken",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "AlreadyRootGuardian",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "AmountOutTooLow",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "BridgeAdapterAlreadySet",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "BridgeConfigNotSet",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "BridgeStateMismatch",
    "type": "error"
  },
  {
    "inputs": [
      {
        "name": "caliberChainId",
        "type": "uint256"
      }
    ],
    "name": "CaliberAccountingStale",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "CaliberAlreadySet",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "CaliberNotEmpty",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "CctpDomainNotRegistered",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "CctpForeignTokenNotRegistered",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "CctpMessageReceptionFailed",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "CreWorkflowIdAlreadyAuthorized",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "CreWorkflowIdNotAuthorized",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "Create3ContractDeploymentFailed",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "Create3ProxyDeploymentFailed",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "DirectManageFlashLoanCall",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ExceededMaxDeposit",
    "type": "error"
  },
  {
    "inputs": [
      {
        "name": "fee",
        "type": "uint256"
      },
      {
        "name": "max",
        "type": "uint256"
      }
    ],
    "name": "ExceededMaxFee",
    "type": "error"
  },
  {
    "inputs": [
      {
        "name": "shares",
        "type": "uint256"
      },
      {
        "name": "max",
        "type": "uint256"
      }
    ],
    "name": "ExceededMaxMint",
    "type": "error"
  },
  {
    "inputs": [
      {
        "name": "assets",
        "type": "uint256"
      },
      {
        "name": "max",
        "type": "uint256"
      }
    ],
    "name": "ExceededMaxWithdraw",
    "type": "error"
  },
  {
    "inputs": [
      {
        "name": "token",
        "type": "address"
      },
      {
        "name": "foreignEvmChainId",
        "type": "uint256"
      }
    ],
    "name": "ForeignTokenNotRegistered",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "FutureSnapshot",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "GroupIdNotProvided",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "HubBridgeAdapterAlreadySet",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "HubBridgeAdapterNotSet",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InstructionsMismatch",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InsufficientBalance",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidAccounting",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidAffectedToken",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidBridgeController",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidBridgeId",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidBridgeTransferRoute",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidCctpMessage",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidChainId",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidCreMetadataLength",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidCreWorkflowId",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidDebtFlag",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidDecimals",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidFeedRoute",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidInputAmount",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidInputToken",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidInstructionProof",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidInstructionType",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidLzSentAmount",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidOft",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidOutputToken",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidPositionChangeDirection",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidRecipientChainId",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidSpokeCaliberMailbox",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidTransferStatus",
    "type": "error"
  },
  {
    "inputs": [
      {
        "name": "token",
        "type": "address"
      },
      {
        "name": "foreignEvmChainId",
        "type": "uint256"
      }
    ],
    "name": "LocalTokenNotRegistered",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "LzEndpointIdNotRegistered",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "LzForeignTokenNotRegistered",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ManageFlashLoanReentrantCall",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "MaxAuthorizedPriceChangeExceeded",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "MaxValueLossExceeded",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "MessageAlreadyAuthorized",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "Migrated",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "MinOutputAmountExceedsInputAmount",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "MismatchedLengths",
    "type": "error"
  },
  {
    "inputs": [
      {
        "name": "groupId",
        "type": "uint256"
      }
    ],
    "name": "MissingInstructionForGroup",
    "type": "error"
  },
  {
    "inputs": [
      {
        "name": "priceFeed",
        "type": "address"
      }
    ],
    "name": "NegativeTokenPrice",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NoPendingUpdate",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NonZeroBalance",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotAccountingAgent",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotBaseToken",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotCaliber",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotController",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotFactory",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotFactoryAuthority",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotFlashLoanModule",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotMachineEndpoint",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotMigrated",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotPendingMachine",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotPreDepositVault",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotRootGuardian",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "OftNotRegistered",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "OngoingCooldown",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "OutTransferNotEnabled",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "PendingBridgeTransfer",
    "type": "error"
  },
  {
    "inputs": [
      {
        "name": "posId",
        "type": "uint256"
      }
    ],
    "name": "PositionAccountingStale",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "PositionDoesNotExist",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "PositionIsGrouped",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "PositionToken",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "PositionTokenIsBaseToken",
    "type": "error"
  },
  {
    "inputs": [
      {
        "name": "token",
        "type": "address"
      }
    ],
    "name": "PriceFeedRouteNotRegistered",
    "type": "error"
  },
  {
    "inputs": [
      {
        "name": "priceFeed",
        "type": "address"
      },
      {
        "name": "updatedAt",
        "type": "uint256"
      }
    ],
    "name": "PriceFeedStale",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ProtectedAccountingAgent",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ProtectedCctpDomain",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ProtectedChainId",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ProtectedRootGuardian",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "RecoveryMode",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "SameRoot",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "SlippageProtection",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "SpokeBridgeAdapterAlreadySet",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "SpokeBridgeAdapterNotSet",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "SpokeCaliberAlreadySet",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "SpokeCaliberNotEnabled",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "StaleSnapshot",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "SwapFailed",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "SwapperTargetsNotSet",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "TargetAlreadyExists",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "UnauthorizedCaller",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "UnauthorizedSource",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "UnexpectedMessage",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ZeroBridgeAdapterAddress",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ZeroChainId",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ZeroGroupId",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ZeroLzEndpointId",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ZeroOftAddress",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ZeroPositionId",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ZeroSalt",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ZeroSpokeCaliberMailboxAddress",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ZeroTokenAddress",
    "type": "error"
  }
] as const;
