// Generated by scripts/update-abis.sh from https://github.com/MakinaHQ/makina-core.git@eb9a2fea6cac9f88783f9c769927ed7e5c2b7fd5
// Source: src/interfaces/IHubCoreRegistry.sol:IHubCoreRegistry. Do not edit.
export const hubCoreRegistryAbi = [
  {
    "inputs": [
      {
        "name": "bridgeId",
        "type": "uint16"
      }
    ],
    "name": "bridgeAdapterBeacon",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "bridgeId",
        "type": "uint16"
      }
    ],
    "name": "bridgeConfig",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "caliberBeacon",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "coreFactory",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "flashLoanModule",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "machineBeacon",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "oracleRegistry",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "preDepositVaultBeacon",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "bridgeId",
        "type": "uint16"
      },
      {
        "name": "_bridgeAdapterBeacon",
        "type": "address"
      }
    ],
    "name": "setBridgeAdapterBeacon",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "bridgeId",
        "type": "uint16"
      },
      {
        "name": "_bridgeConfig",
        "type": "address"
      }
    ],
    "name": "setBridgeConfig",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "_caliberBeacon",
        "type": "address"
      }
    ],
    "name": "setCaliberBeacon",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "_coreFactory",
        "type": "address"
      }
    ],
    "name": "setCoreFactory",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "_flashLoanModule",
        "type": "address"
      }
    ],
    "name": "setFlashLoanModule",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "_machineBeacon",
        "type": "address"
      }
    ],
    "name": "setMachineBeacon",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "_oracleRegistry",
        "type": "address"
      }
    ],
    "name": "setOracleRegistry",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "_preDepositVaultBeacon",
        "type": "address"
      }
    ],
    "name": "setPreDepositVaultBeacon",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "_swapModule",
        "type": "address"
      }
    ],
    "name": "setSwapModule",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "_tokenRegistry",
        "type": "address"
      }
    ],
    "name": "setTokenRegistry",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "swapModule",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "tokenRegistry",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "bridgeId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "name": "oldBridgeAdapterBeacon",
        "type": "address"
      },
      {
        "indexed": true,
        "name": "newBridgeAdapterBeacon",
        "type": "address"
      }
    ],
    "name": "BridgeAdapterBeaconChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "bridgeId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "name": "oldBridgeConfig",
        "type": "address"
      },
      {
        "indexed": true,
        "name": "newBridgeConfig",
        "type": "address"
      }
    ],
    "name": "BridgeConfigChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "oldCaliberBeacon",
        "type": "address"
      },
      {
        "indexed": true,
        "name": "newCaliberBeacon",
        "type": "address"
      }
    ],
    "name": "CaliberBeaconChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "oldCoreFactory",
        "type": "address"
      },
      {
        "indexed": true,
        "name": "newCoreFactory",
        "type": "address"
      }
    ],
    "name": "CoreFactoryChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "oldFlashLoanModule",
        "type": "address"
      },
      {
        "indexed": true,
        "name": "newFlashLoanModule",
        "type": "address"
      }
    ],
    "name": "FlashLoanModuleChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "oldMachineBeacon",
        "type": "address"
      },
      {
        "indexed": true,
        "name": "newMachineBeacon",
        "type": "address"
      }
    ],
    "name": "MachineBeaconChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "oldOracleRegistry",
        "type": "address"
      },
      {
        "indexed": true,
        "name": "newOracleRegistry",
        "type": "address"
      }
    ],
    "name": "OracleRegistryChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "oldPreDepositVaultBeacon",
        "type": "address"
      },
      {
        "indexed": true,
        "name": "newPreDepositVaultBeacon",
        "type": "address"
      }
    ],
    "name": "PreDepositVaultBeaconChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "oldSwapModule",
        "type": "address"
      },
      {
        "indexed": true,
        "name": "newSwapModule",
        "type": "address"
      }
    ],
    "name": "SwapModuleChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "oldTokenRegistry",
        "type": "address"
      },
      {
        "indexed": true,
        "name": "newTokenRegistry",
        "type": "address"
      }
    ],
    "name": "TokenRegistryChanged",
    "type": "event"
  }
] as const;
