// Generated by scripts/update-abis.sh from https://github.com/MakinaHQ/makina-core.git@eb9a2fea6cac9f88783f9c769927ed7e5c2b7fd5
// Source: src/interfaces/IHubCoreFactory.sol:IHubCoreFactory. Do not edit.
export const hubCoreFactoryAbi = [
  {
    "inputs": [
      {
        "name": "controller",
        "type": "address"
      },
      {
        "components": [
          {
            "name": "bridgeId",
            "type": "uint16"
          },
          {
            "name": "initData",
            "type": "bytes"
          },
          {
            "name": "initialMaxBridgeLossBps",
            "type": "uint256"
          }
        ],
        "name": "baParams",
        "type": "tuple"
      }
    ],
    "name": "createBridgeAdapter",
    "outputs": [
      {
        "name": "adapter",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "name": "initialDepositor",
            "type": "address"
          },
          {
            "name": "initialRedeemer",
            "type": "address"
          },
          {
            "name": "initialFeeManager",
            "type": "address"
          },
          {
            "name": "initialCaliberStaleThreshold",
            "type": "uint256"
          },
          {
            "name": "initialMaxFixedFeeAccrualRate",
            "type": "uint256"
          },
          {
            "name": "initialMaxPerfFeeAccrualRate",
            "type": "uint256"
          },
          {
            "name": "initialFeeMintCooldown",
            "type": "uint256"
          },
          {
            "name": "initialShareLimit",
            "type": "uint256"
          },
          {
            "name": "initialMaxSharePriceChangeRate",
            "type": "uint256"
          }
        ],
        "name": "mParams",
        "type": "tuple"
      },
      {
        "components": [
          {
            "name": "initialPositionStaleThreshold",
            "type": "uint256"
          },
          {
            "name": "initialAllowedInstrRoot",
            "type": "bytes32"
          },
          {
            "name": "initialTimelockDuration",
            "type": "uint256"
          },
          {
            "name": "initialMaxPositionIncreaseLossBps",
            "type": "uint256"
          },
          {
            "name": "initialMaxPositionDecreaseLossBps",
            "type": "uint256"
          },
          {
            "name": "initialMaxSwapLossBps",
            "type": "uint256"
          },
          {
            "name": "initialCooldownDuration",
            "type": "uint256"
          },
          {
            "name": "initialBaseTokens",
            "type": "address[]"
          }
        ],
        "name": "cParams",
        "type": "tuple"
      },
      {
        "components": [
          {
            "name": "initialMechanic",
            "type": "address"
          },
          {
            "name": "initialSecurityCouncil",
            "type": "address"
          },
          {
            "name": "initialRiskManager",
            "type": "address"
          },
          {
            "name": "initialRiskManagerTimelock",
            "type": "address"
          },
          {
            "name": "initialAuthority",
            "type": "address"
          },
          {
            "name": "initialRestrictedAccountingMode",
            "type": "bool"
          },
          {
            "name": "initialAccountingAgents",
            "type": "address[]"
          }
        ],
        "name": "mgParams",
        "type": "tuple"
      },
      {
        "components": [
          {
            "name": "initialCreWorkflowIds",
            "type": "bytes32[]"
          }
        ],
        "name": "sscParams",
        "type": "tuple"
      },
      {
        "components": [
          {
            "name": "bridgeId",
            "type": "uint16"
          },
          {
            "name": "initData",
            "type": "bytes"
          },
          {
            "name": "initialMaxBridgeLossBps",
            "type": "uint256"
          }
        ],
        "name": "baParams",
        "type": "tuple[]"
      },
      {
        "name": "accountingToken",
        "type": "address"
      },
      {
        "name": "tokenName",
        "type": "string"
      },
      {
        "name": "tokenSymbol",
        "type": "string"
      },
      {
        "name": "salt",
        "type": "bytes32"
      },
      {
        "name": "setupAMFunctionRoles",
        "type": "bool"
      }
    ],
    "name": "createMachine",
    "outputs": [
      {
        "name": "machine",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "name": "initialDepositor",
            "type": "address"
          },
          {
            "name": "initialRedeemer",
            "type": "address"
          },
          {
            "name": "initialFeeManager",
            "type": "address"
          },
          {
            "name": "initialCaliberStaleThreshold",
            "type": "uint256"
          },
          {
            "name": "initialMaxFixedFeeAccrualRate",
            "type": "uint256"
          },
          {
            "name": "initialMaxPerfFeeAccrualRate",
            "type": "uint256"
          },
          {
            "name": "initialFeeMintCooldown",
            "type": "uint256"
          },
          {
            "name": "initialShareLimit",
            "type": "uint256"
          },
          {
            "name": "initialMaxSharePriceChangeRate",
            "type": "uint256"
          }
        ],
        "name": "mParams",
        "type": "tuple"
      },
      {
        "components": [
          {
            "name": "initialPositionStaleThreshold",
            "type": "uint256"
          },
          {
            "name": "initialAllowedInstrRoot",
            "type": "bytes32"
          },
          {
            "name": "initialTimelockDuration",
            "type": "uint256"
          },
          {
            "name": "initialMaxPositionIncreaseLossBps",
            "type": "uint256"
          },
          {
            "name": "initialMaxPositionDecreaseLossBps",
            "type": "uint256"
          },
          {
            "name": "initialMaxSwapLossBps",
            "type": "uint256"
          },
          {
            "name": "initialCooldownDuration",
            "type": "uint256"
          },
          {
            "name": "initialBaseTokens",
            "type": "address[]"
          }
        ],
        "name": "cParams",
        "type": "tuple"
      },
      {
        "components": [
          {
            "name": "initialMechanic",
            "type": "address"
          },
          {
            "name": "initialSecurityCouncil",
            "type": "address"
          },
          {
            "name": "initialRiskManager",
            "type": "address"
          },
          {
            "name": "initialRiskManagerTimelock",
            "type": "address"
          },
          {
            "name": "initialAuthority",
            "type": "address"
          },
          {
            "name": "initialRestrictedAccountingMode",
            "type": "bool"
          },
          {
            "name": "initialAccountingAgents",
            "type": "address[]"
          }
        ],
        "name": "mgParams",
        "type": "tuple"
      },
      {
        "components": [
          {
            "name": "initialCreWorkflowIds",
            "type": "bytes32[]"
          }
        ],
        "name": "sscParams",
        "type": "tuple"
      },
      {
        "components": [
          {
            "name": "bridgeId",
            "type": "uint16"
          },
          {
            "name": "initData",
            "type": "bytes"
          },
          {
            "name": "initialMaxBridgeLossBps",
            "type": "uint256"
          }
        ],
        "name": "baParams",
        "type": "tuple[]"
      },
      {
        "name": "preDepositVault",
        "type": "address"
      },
      {
        "name": "salt",
        "type": "bytes32"
      },
      {
        "name": "setupAMFunctionRoles",
        "type": "bool"
      }
    ],
    "name": "createMachineFromPreDeposit",
    "outputs": [
      {
        "name": "machine",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "name": "initialShareLimit",
            "type": "uint256"
          },
          {
            "name": "initialWhitelistMode",
            "type": "bool"
          },
          {
            "name": "initialRiskManager",
            "type": "address"
          },
          {
            "name": "initialAuthority",
            "type": "address"
          }
        ],
        "name": "params",
        "type": "tuple"
      },
      {
        "name": "depositToken",
        "type": "address"
      },
      {
        "name": "accountingToken",
        "type": "address"
      },
      {
        "name": "tokenName",
        "type": "string"
      },
      {
        "name": "tokenSymbol",
        "type": "string"
      },
      {
        "name": "setupAMFunctionRoles",
        "type": "bool"
      }
    ],
    "name": "createPreDepositVault",
    "outputs": [
      {
        "name": "preDepositVault",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "adapter",
        "type": "address"
      }
    ],
    "name": "isBridgeAdapter",
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "machine",
        "type": "address"
      }
    ],
    "name": "isMachine",
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "preDepositVault",
        "type": "address"
      }
    ],
    "name": "isPreDepositVault",
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "controller",
        "type": "address"
      },
      {
        "indexed": true,
        "name": "bridgeId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "name": "adapter",
        "type": "address"
      }
    ],
    "name": "BridgeAdapterCreated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "machine",
        "type": "address"
      },
      {
        "indexed": true,
        "name": "shareToken",
        "type": "address"
      }
    ],
    "name": "MachineCreated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "preDepositVault",
        "type": "address"
      },
      {
        "indexed": true,
        "name": "shareToken",
        "type": "address"
      }
    ],
    "name": "PreDepositVaultCreated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "shareToken",
        "type": "address"
      }
    ],
    "name": "ShareTokenCreated",
    "type": "event"
  }
] as const;
