// Generated by scripts/update-abis.sh from https://github.com/MakinaHQ/makina-periphery.git@72aab70ea8dcedba4658cd339dd07022e28ca1b2
// Source: src/interfaces/IHubPeripheryRegistry.sol:IHubPeripheryRegistry. Do not edit.
export const hubPeripheryRegistryAbi = [
  {
    "inputs": [
      {
        "name": "implemId",
        "type": "uint16"
      }
    ],
    "name": "depositorBeacon",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "implemId",
        "type": "uint16"
      }
    ],
    "name": "feeManagerBeacon",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "peripheryFactory",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "implemId",
        "type": "uint16"
      }
    ],
    "name": "redeemerBeacon",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "securityModuleBeacon",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "implemId",
        "type": "uint16"
      },
      {
        "name": "_depositorBeacon",
        "type": "address"
      }
    ],
    "name": "setDepositorBeacon",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "implemId",
        "type": "uint16"
      },
      {
        "name": "_feeManagerBeacon",
        "type": "address"
      }
    ],
    "name": "setFeeManagerBeacon",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "_peripheryFactory",
        "type": "address"
      }
    ],
    "name": "setPeripheryFactory",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "implemId",
        "type": "uint16"
      },
      {
        "name": "_redeemerBeacon",
        "type": "address"
      }
    ],
    "name": "setRedeemerBeacon",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "_securityModuleBeacon",
        "type": "address"
      }
    ],
    "name": "setSecurityModuleBeacon",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "implemId",
        "type": "uint16"
      },
      {
        "indexed": true,
        "name": "oldDepositorBeacon",
        "type": "address"
      },
      {
        "indexed": true,
        "name": "newDepositorBeacon",
        "type": "address"
      }
    ],
    "name": "DepositorBeaconChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "implemId",
        "type": "uint16"
      },
      {
        "indexed": true,
        "name": "oldFeeManagerBeacon",
        "type": "address"
      },
      {
        "indexed": true,
        "name": "newFeeManagerBeacon",
        "type": "address"
      }
    ],
    "name": "FeeManagerBeaconChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "oldPeripheryFactory",
        "type": "address"
      },
      {
        "indexed": true,
        "name": "newPeripheryFactory",
        "type": "address"
      }
    ],
    "name": "PeripheryFactoryChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "implemId",
        "type": "uint16"
      },
      {
        "indexed": true,
        "name": "oldRedeemerBeacon",
        "type": "address"
      },
      {
        "indexed": true,
        "name": "newRedeemerBeacon",
        "type": "address"
      }
    ],
    "name": "RedeemerBeaconChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "oldSecurityModuleBeacon",
        "type": "address"
      },
      {
        "indexed": true,
        "name": "newSecurityModuleBeacon",
        "type": "address"
      }
    ],
    "name": "SecurityModuleBeaconChanged",
    "type": "event"
  }
] as const;
