// Generated by scripts/update-abis.sh from https://github.com/MakinaHQ/makina-periphery.git@72aab70ea8dcedba4658cd339dd07022e28ca1b2
// Source: src/interfaces/IHubPeripheryFactory.sol:IHubPeripheryFactory. Do not edit.
export const hubPeripheryFactoryAbi = [
  {
    "inputs": [
      {
        "name": "implemId",
        "type": "uint16"
      },
      {
        "name": "initializationData",
        "type": "bytes"
      }
    ],
    "name": "createDepositor",
    "outputs": [
      {
        "name": "depositor",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "implemId",
        "type": "uint16"
      },
      {
        "name": "initializationData",
        "type": "bytes"
      }
    ],
    "name": "createFeeManager",
    "outputs": [
      {
        "name": "feeManager",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "implemId",
        "type": "uint16"
      },
      {
        "name": "initializationData",
        "type": "bytes"
      }
    ],
    "name": "createRedeemer",
    "outputs": [
      {
        "name": "redeemer",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "name": "machineShare",
            "type": "address"
          },
          {
            "name": "initialCooldownDuration",
            "type": "uint256"
          },
          {
            "name": "initialMaxSlashableBps",
            "type": "uint256"
          },
          {
            "name": "initialMinBalanceAfterSlash",
            "type": "uint256"
          }
        ],
        "name": "smParams",
        "type": "tuple"
      }
    ],
    "name": "createSecurityModule",
    "outputs": [
      {
        "name": "securityModule",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "depositor",
        "type": "address"
      }
    ],
    "name": "depositorImplemId",
    "outputs": [
      {
        "name": "",
        "type": "uint16"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "feeManager",
        "type": "address"
      }
    ],
    "name": "feeManagerImplemId",
    "outputs": [
      {
        "name": "",
        "type": "uint16"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "depositor",
        "type": "address"
      }
    ],
    "name": "isDepositor",
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "feeManager",
        "type": "address"
      }
    ],
    "name": "isFeeManager",
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "redeemer",
        "type": "address"
      }
    ],
    "name": "isRedeemer",
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "securityModule",
        "type": "address"
      }
    ],
    "name": "isSecurityModule",
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "redeemer",
        "type": "address"
      }
    ],
    "name": "redeemerImplemId",
    "outputs": [
      {
        "name": "",
        "type": "uint16"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "machinePeriphery",
        "type": "address"
      },
      {
        "name": "machine",
        "type": "address"
      }
    ],
    "name": "setMachine",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "feeManager",
        "type": "address"
      },
      {
        "name": "securityModule",
        "type": "address"
      }
    ],
    "name": "setSecurityModule",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "depositor",
        "type": "address"
      },
      {
        "indexed": true,
        "name": "implemId",
        "type": "uint16"
      }
    ],
    "name": "DepositorCreated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "feeManager",
        "type": "address"
      },
      {
        "indexed": true,
        "name": "implemId",
        "type": "uint16"
      }
    ],
    "name": "FeeManagerCreated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "redeemer",
        "type": "address"
      },
      {
        "indexed": true,
        "name": "implemId",
        "type": "uint16"
      }
    ],
    "name": "RedeemerCreated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "securityModule",
        "type": "address"
      }
    ],
    "name": "SecurityModuleCreated",
    "type": "event"
  }
] as const;
