// Generated by scripts/update-abis.sh from https://github.com/MakinaHQ/makina-core.git@eb9a2fea6cac9f88783f9c769927ed7e5c2b7fd5
// Source: src/interfaces/IMachine.sol:IMachine. Do not edit.
export const machineAbi = [
  {
    "inputs": [],
    "name": "accountingToken",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "newAgent",
        "type": "address"
      }
    ],
    "name": "addAccountingAgent",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "newCreWorkflowId",
        "type": "bytes32"
      }
    ],
    "name": "addCreWorkflowId",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "bridgeId",
        "type": "uint16"
      },
      {
        "name": "messageHash",
        "type": "bytes32"
      }
    ],
    "name": "authorizeInBridgeTransfer",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "caliberStaleThreshold",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "bridgeId",
        "type": "uint16"
      },
      {
        "name": "transferId",
        "type": "uint256"
      }
    ],
    "name": "cancelOutBridgeTransfer",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "bridgeId",
        "type": "uint16"
      },
      {
        "name": "transferId",
        "type": "uint256"
      }
    ],
    "name": "claimInBridgeTransfer",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "shares",
        "type": "uint256"
      }
    ],
    "name": "convertToAssets",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "assets",
        "type": "uint256"
      }
    ],
    "name": "convertToShares",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "creForwarder",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "assets",
        "type": "uint256"
      },
      {
        "name": "receiver",
        "type": "address"
      },
      {
        "name": "minShares",
        "type": "uint256"
      },
      {
        "name": "referralKey",
        "type": "bytes32"
      }
    ],
    "name": "deposit",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "depositor",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "bridgeId",
        "type": "uint16"
      }
    ],
    "name": "disableOutTransfer",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "chainId",
        "type": "uint256"
      }
    ],
    "name": "disableSpokeCaliber",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "bridgeId",
        "type": "uint16"
      }
    ],
    "name": "enableOutTransfer",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "chainId",
        "type": "uint256"
      }
    ],
    "name": "enableSpokeCaliber",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "feeManager",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "feeMintCooldown",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "bridgeId",
        "type": "uint16"
      }
    ],
    "name": "getBridgeAdapter",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "idx",
        "type": "uint256"
      }
    ],
    "name": "getIdleToken",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getIdleTokensLength",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "bridgeId",
        "type": "uint16"
      }
    ],
    "name": "getMaxBridgeLossBps",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "chainId",
        "type": "uint256"
      },
      {
        "name": "bridgeId",
        "type": "uint16"
      }
    ],
    "name": "getSpokeBridgeAdapter",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "chainId",
        "type": "uint256"
      }
    ],
    "name": "getSpokeCaliberMailbox",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "chainId",
        "type": "uint256"
      }
    ],
    "name": "getSpokeCaliberNetAum",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      },
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getSpokeCalibersLength",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "idx",
        "type": "uint256"
      }
    ],
    "name": "getSpokeChainId",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "hubCaliber",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "name": "initialDepositor",
            "type": "address"
          },
          {
            "name": "initialRedeemer",
            "type": "address"
          },
          {
            "name": "initialFeeManager",
            "type": "address"
          },
          {
            "name": "initialCaliberStaleThreshold",
            "type": "uint256"
          },
          {
            "name": "initialMaxFixedFeeAccrualRate",
            "type": "uint256"
          },
          {
            "name": "initialMaxPerfFeeAccrualRate",
            "type": "uint256"
          },
          {
            "name": "initialFeeMintCooldown",
            "type": "uint256"
          },
          {
            "name": "initialShareLimit",
            "type": "uint256"
          },
          {
            "name": "initialMaxSharePriceChangeRate",
            "type": "uint256"
          }
        ],
        "name": "mParams",
        "type": "tuple"
      },
      {
        "components": [
          {
            "name": "initialMechanic",
            "type": "address"
          },
          {
            "name": "initialSecurityCouncil",
            "type": "address"
          },
          {
            "name": "initialRiskManager",
            "type": "address"
          },
          {
            "name": "initialRiskManagerTimelock",
            "type": "address"
          },
          {
            "name": "initialAuthority",
            "type": "address"
          },
          {
            "name": "initialRestrictedAccountingMode",
            "type": "bool"
          },
          {
            "name": "initialAccountingAgents",
            "type": "address[]"
          }
        ],
        "name": "mgParams",
        "type": "tuple"
      },
      {
        "components": [
          {
            "name": "initialCreWorkflowIds",
            "type": "bytes32[]"
          }
        ],
        "name": "sscParams",
        "type": "tuple"
      },
      {
        "name": "_preDepositVault",
        "type": "address"
      },
      {
        "name": "_shareToken",
        "type": "address"
      },
      {
        "name": "_accountingToken",
        "type": "address"
      },
      {
        "name": "_hubCaliber",
        "type": "address"
      }
    ],
    "name": "initialize",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "user",
        "type": "address"
      }
    ],
    "name": "isAccountingAgent",
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "user",
        "type": "address"
      }
    ],
    "name": "isAccountingAuthorized",
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "bridgeId",
        "type": "uint16"
      }
    ],
    "name": "isBridgeSupported",
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "creWorkflowId",
        "type": "bytes32"
      }
    ],
    "name": "isCreWorkflowIdAuthorized",
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "token",
        "type": "address"
      }
    ],
    "name": "isIdleToken",
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "bridgeId",
        "type": "uint16"
      }
    ],
    "name": "isOutTransferEnabled",
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "chainId",
        "type": "uint256"
      }
    ],
    "name": "isSpokeCaliberEnabled",
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "lastGlobalAccountingTime",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "lastTotalAum",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "token",
        "type": "address"
      },
      {
        "name": "amount",
        "type": "uint256"
      },
      {
        "name": "data",
        "type": "bytes"
      }
    ],
    "name": "manageTransfer",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "maxFixedFeeAccrualRate",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "maxMint",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "maxPerfFeeAccrualRate",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "maxSharePriceChangeRate",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "maxWithdraw",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "mechanic",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "metadata",
        "type": "bytes"
      },
      {
        "name": "report",
        "type": "bytes"
      }
    ],
    "name": "onReport",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "operator",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "recoveryMode",
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "shares",
        "type": "uint256"
      },
      {
        "name": "receiver",
        "type": "address"
      },
      {
        "name": "minAssets",
        "type": "uint256"
      }
    ],
    "name": "redeem",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "redeemer",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "agent",
        "type": "address"
      }
    ],
    "name": "removeAccountingAgent",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "creWorkflowId",
        "type": "bytes32"
      }
    ],
    "name": "removeCreWorkflowId",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "token",
        "type": "address"
      }
    ],
    "name": "resetBridgingState",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "restrictedAccountingMode",
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "riskManager",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "riskManagerTimelock",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "securityCouncil",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "bridgeId",
        "type": "uint16"
      },
      {
        "name": "transferId",
        "type": "uint256"
      },
      {
        "name": "data",
        "type": "bytes"
      }
    ],
    "name": "sendOutBridgeTransfer",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "bridgeId",
        "type": "uint16"
      },
      {
        "name": "bridgeAdapter",
        "type": "address"
      },
      {
        "name": "initialMaxBridgeLossBps",
        "type": "uint256"
      }
    ],
    "name": "setBridgeAdapter",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "newCaliberStaleThreshold",
        "type": "uint256"
      }
    ],
    "name": "setCaliberStaleThreshold",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "newDepositor",
        "type": "address"
      }
    ],
    "name": "setDepositor",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "newFeeManager",
        "type": "address"
      }
    ],
    "name": "setFeeManager",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "newFeeMintCooldown",
        "type": "uint256"
      }
    ],
    "name": "setFeeMintCooldown",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "bridgeId",
        "type": "uint16"
      },
      {
        "name": "maxBridgeLossBps",
        "type": "uint256"
      }
    ],
    "name": "setMaxBridgeLossBps",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "newMaxAccrualRate",
        "type": "uint256"
      }
    ],
    "name": "setMaxFixedFeeAccrualRate",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "newMaxAccrualRate",
        "type": "uint256"
      }
    ],
    "name": "setMaxPerfFeeAccrualRate",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "newMaxSharePriceChangeRate",
        "type": "uint256"
      }
    ],
    "name": "setMaxSharePriceChangeRate",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "newMechanic",
        "type": "address"
      }
    ],
    "name": "setMechanic",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "enabled",
        "type": "bool"
      }
    ],
    "name": "setRecoveryMode",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "newRedeemer",
        "type": "address"
      }
    ],
    "name": "setRedeemer",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "enabled",
        "type": "bool"
      }
    ],
    "name": "setRestrictedAccountingMode",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "newRiskManager",
        "type": "address"
      }
    ],
    "name": "setRiskManager",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "newRiskManagerTimelock",
        "type": "address"
      }
    ],
    "name": "setRiskManagerTimelock",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "newSecurityCouncil",
        "type": "address"
      }
    ],
    "name": "setSecurityCouncil",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "newShareLimit",
        "type": "uint256"
      }
    ],
    "name": "setShareLimit",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "chainId",
        "type": "uint256"
      },
      {
        "name": "bridgeId",
        "type": "uint16"
      },
      {
        "name": "adapter",
        "type": "address"
      }
    ],
    "name": "setSpokeBridgeAdapter",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "chainId",
        "type": "uint256"
      },
      {
        "name": "spokeCaliberMailbox",
        "type": "address"
      },
      {
        "name": "bridges",
        "type": "uint16[]"
      },
      {
        "name": "adapters",
        "type": "address[]"
      }
    ],
    "name": "setSpokeCaliber",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "shareLimit",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "shareToken",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "interfaceId",
        "type": "bytes4"
      }
    ],
    "name": "supportsInterface",
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "token",
        "type": "address"
      },
      {
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "transferToHubCaliber",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "bridgeId",
        "type": "uint16"
      },
      {
        "name": "chainId",
        "type": "uint256"
      },
      {
        "name": "token",
        "type": "address"
      },
      {
        "name": "amount",
        "type": "uint256"
      },
      {
        "name": "minOutputAmount",
        "type": "uint256"
      }
    ],
    "name": "transferToSpokeCaliber",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "updateTotalAum",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "newAgent",
        "type": "address"
      }
    ],
    "name": "AccountingAgentAdded",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "agent",
        "type": "address"
      }
    ],
    "name": "AccountingAgentRemoved",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "bridgeId",
        "type": "uint16"
      },
      {
        "indexed": true,
        "name": "adapter",
        "type": "address"
      }
    ],
    "name": "BridgeAdapterSet",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "token",
        "type": "address"
      }
    ],
    "name": "BridgingStateReset",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "oldThreshold",
        "type": "uint256"
      },
      {
        "indexed": true,
        "name": "newThreshold",
        "type": "uint256"
      }
    ],
    "name": "CaliberStaleThresholdChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "newCreWorkflowId",
        "type": "bytes32"
      }
    ],
    "name": "CreWorkflowIdAdded",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "creWorkflowId",
        "type": "bytes32"
      }
    ],
    "name": "CreWorkflowIdRemoved",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "sender",
        "type": "address"
      },
      {
        "indexed": true,
        "name": "receiver",
        "type": "address"
      },
      {
        "indexed": false,
        "name": "assets",
        "type": "uint256"
      },
      {
        "indexed": false,
        "name": "shares",
        "type": "uint256"
      },
      {
        "indexed": true,
        "name": "referralKey",
        "type": "bytes32"
      }
    ],
    "name": "Deposit",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "oldDepositor",
        "type": "address"
      },
      {
        "indexed": true,
        "name": "newDepositor",
        "type": "address"
      }
    ],
    "name": "DepositorChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "oldFeeManager",
        "type": "address"
      },
      {
        "indexed": true,
        "name": "newFeeManager",
        "type": "address"
      }
    ],
    "name": "FeeManagerChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "oldFeeMintCooldown",
        "type": "uint256"
      },
      {
        "indexed": true,
        "name": "newFeeMintCooldown",
        "type": "uint256"
      }
    ],
    "name": "FeeMintCooldownChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "name": "shares",
        "type": "uint256"
      }
    ],
    "name": "FeesMinted",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "bridgeId",
        "type": "uint16"
      },
      {
        "indexed": true,
        "name": "oldMaxBridgeLossBps",
        "type": "uint256"
      },
      {
        "indexed": true,
        "name": "newMaxBridgeLossBps",
        "type": "uint256"
      }
    ],
    "name": "MaxBridgeLossBpsChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "oldMaxAccrualRate",
        "type": "uint256"
      },
      {
        "indexed": true,
        "name": "newMaxAccrualRate",
        "type": "uint256"
      }
    ],
    "name": "MaxFixedFeeAccrualRateChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "oldMaxAccrualRate",
        "type": "uint256"
      },
      {
        "indexed": true,
        "name": "newMaxAccrualRate",
        "type": "uint256"
      }
    ],
    "name": "MaxPerfFeeAccrualRateChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "oldMaxChangeRate",
        "type": "uint256"
      },
      {
        "indexed": true,
        "name": "newMaxChangeRate",
        "type": "uint256"
      }
    ],
    "name": "MaxSharePriceChangeRateChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "oldMechanic",
        "type": "address"
      },
      {
        "indexed": true,
        "name": "newMechanic",
        "type": "address"
      }
    ],
    "name": "MechanicChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "bridgeId",
        "type": "uint16"
      }
    ],
    "name": "OutTransferDisabled",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "bridgeId",
        "type": "uint16"
      }
    ],
    "name": "OutTransferEnabled",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "name": "recoveryMode",
        "type": "bool"
      }
    ],
    "name": "RecoveryModeChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "owner",
        "type": "address"
      },
      {
        "indexed": true,
        "name": "receiver",
        "type": "address"
      },
      {
        "indexed": false,
        "name": "assets",
        "type": "uint256"
      },
      {
        "indexed": false,
        "name": "shares",
        "type": "uint256"
      }
    ],
    "name": "Redeem",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "oldRedeemer",
        "type": "address"
      },
      {
        "indexed": true,
        "name": "newRedeemer",
        "type": "address"
      }
    ],
    "name": "RedeemerChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "name": "restrictedAccountingMode",
        "type": "bool"
      }
    ],
    "name": "RestrictedAccountingModeChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "oldRiskManager",
        "type": "address"
      },
      {
        "indexed": true,
        "name": "newRiskManager",
        "type": "address"
      }
    ],
    "name": "RiskManagerChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "oldRiskManagerTimelock",
        "type": "address"
      },
      {
        "indexed": true,
        "name": "newRiskManagerTimelock",
        "type": "address"
      }
    ],
    "name": "RiskManagerTimelockChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "oldSecurityCouncil",
        "type": "address"
      },
      {
        "indexed": true,
        "name": "newSecurityCouncil",
        "type": "address"
      }
    ],
    "name": "SecurityCouncilChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "oldShareLimit",
        "type": "uint256"
      },
      {
        "indexed": true,
        "name": "newShareLimit",
        "type": "uint256"
      }
    ],
    "name": "ShareLimitChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "chainId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "name": "bridgeId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "name": "adapter",
        "type": "address"
      }
    ],
    "name": "SpokeBridgeAdapterSet",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "chainId",
        "type": "uint256"
      }
    ],
    "name": "SpokeCaliberDisabled",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "chainId",
        "type": "uint256"
      }
    ],
    "name": "SpokeCaliberEnabled",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "chainId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "name": "caliberMailbox",
        "type": "address"
      }
    ],
    "name": "SpokeCaliberMailboxSet",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "name": "totalAum",
        "type": "uint256"
      }
    ],
    "name": "TotalAumUpdated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "chainId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "name": "token",
        "type": "address"
      },
      {
        "indexed": false,
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "TransferToCaliber",
    "type": "event"
  }
] as const;
