// Generated by scripts/update-abis.sh from https://github.com/MakinaHQ/makina-periphery.git@72aab70ea8dcedba4658cd339dd07022e28ca1b2
// Source: src/libraries/Errors.sol:Errors. Do not edit.
export const peripheryErrorsAbi = [
  {
    "inputs": [],
    "name": "AlreadyFinalized",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "AmountTooLow",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "CooldownExpired",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "CooldownOngoing",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "FinalizationDelayPending",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "GreaterThanCurrentWatermark",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidDepositorImplemId",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidFeeManagerImplemId",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidFeeSplit",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidMachinePeriphery",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidRedeemerImplemId",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidSecurityModule",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "MachineAlreadySet",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "MachineNotSet",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "MaxBpsValueExceeded",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "MaxFeeRateValueExceeded",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "MaxSlashableExceeded",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotDepositor",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotFeeManager",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotFinalized",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotImplemented",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotMachine",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotRedeemer",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotSecurityModule",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "SanctionedCaller",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "SecurityModuleAlreadySet",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "SlashingSettlementOngoing",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ZeroMachineAddress",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ZeroShares",
    "type": "error"
  }
] as const;
