// Generated by scripts/update-abis.sh from https://github.com/MakinaHQ/makina-core.git@eb9a2fea6cac9f88783f9c769927ed7e5c2b7fd5
// Source: lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/token/ERC20/utils/SafeERC20.sol:SafeERC20. Do not edit.
export const safeErc20ErrorsAbi = [
  {
    "inputs": [
      {
        "name": "spender",
        "type": "address"
      },
      {
        "name": "currentAllowance",
        "type": "uint256"
      },
      {
        "name": "requestedDecrease",
        "type": "uint256"
      }
    ],
    "name": "SafeERC20FailedDecreaseAllowance",
    "type": "error"
  },
  {
    "inputs": [
      {
        "name": "token",
        "type": "address"
      }
    ],
    "name": "SafeERC20FailedOperation",
    "type": "error"
  }
] as const;
