// Generated by scripts/update-abis.sh from https://github.com/MakinaHQ/makina-periphery.git@72aab70ea8dcedba4658cd339dd07022e28ca1b2
// Source: src/interfaces/IChainalysisSanctionsList.sol:IChainalysisSanctionsList. Do not edit.
export const sanctionsOracleAbi = [
  {
    "inputs": [
      {
        "name": "addr",
        "type": "address"
      }
    ],
    "name": "isSanctioned",
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;
