// Generated by scripts/update-abis.sh from https://github.com/MakinaHQ/makina-periphery.git@72aab70ea8dcedba4658cd339dd07022e28ca1b2
// Source: src/interfaces/IWatermarkFeeManager.sol:IWatermarkFeeManager. Do not edit.
export const watermarkFeeManagerAbi = [
  {
    "inputs": [
      {
        "name": "shareSupply",
        "type": "uint256"
      },
      {
        "name": "elapsedTime",
        "type": "uint256"
      }
    ],
    "name": "calculateFixedFee",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "currentShareSupply",
        "type": "uint256"
      },
      {
        "name": "oldSharePrice",
        "type": "uint256"
      },
      {
        "name": "newSharePrice",
        "type": "uint256"
      },
      {
        "name": "elapsedTime",
        "type": "uint256"
      }
    ],
    "name": "calculatePerformanceFee",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "fixedFee",
        "type": "uint256"
      },
      {
        "name": "perfFee",
        "type": "uint256"
      }
    ],
    "name": "distributeFees",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getRestrictedFeeConfigSelectors",
    "outputs": [
      {
        "name": "",
        "type": "bytes4[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "_data",
        "type": "bytes"
      }
    ],
    "name": "initialize",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "machine",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "mgmtFeeRatePerSecond",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "mgmtFeeReceivers",
    "outputs": [
      {
        "name": "",
        "type": "address[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "mgmtFeeSplitBps",
    "outputs": [
      {
        "name": "",
        "type": "uint256[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "perfFeeRate",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "perfFeeReceivers",
    "outputs": [
      {
        "name": "",
        "type": "address[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "perfFeeSplitBps",
    "outputs": [
      {
        "name": "",
        "type": "uint256[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "sharePrice",
        "type": "uint256"
      }
    ],
    "name": "resetSharePriceWatermark",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "securityModule",
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "_machine",
        "type": "address"
      }
    ],
    "name": "setMachine",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "newMgmtFeeRatePerSecond",
        "type": "uint256"
      }
    ],
    "name": "setMgmtFeeRatePerSecond",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "newMgmtFeeReceivers",
        "type": "address[]"
      },
      {
        "name": "newMgmtFeeSplitBps",
        "type": "uint256[]"
      }
    ],
    "name": "setMgmtFeeSplit",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "newPerfFeeRate",
        "type": "uint256"
      }
    ],
    "name": "setPerfFeeRate",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "newPerfFeeReceivers",
        "type": "address[]"
      },
      {
        "name": "newPerfFeeSplitBps",
        "type": "uint256[]"
      }
    ],
    "name": "setPerfFeeSplit",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "_securityModule",
        "type": "address"
      }
    ],
    "name": "setSecurityModule",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "name": "newSmFeeRatePerSecond",
        "type": "uint256"
      }
    ],
    "name": "setSmFeeRatePerSecond",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "sharePriceWatermark",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "smFeeRatePerSecond",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "machine",
        "type": "address"
      }
    ],
    "name": "MachineSet",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "name": "oldRate",
        "type": "uint256"
      },
      {
        "indexed": false,
        "name": "newRate",
        "type": "uint256"
      }
    ],
    "name": "MgmtFeeRatePerSecondChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [],
    "name": "MgmtFeeSplitChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "name": "oldRate",
        "type": "uint256"
      },
      {
        "indexed": false,
        "name": "newRate",
        "type": "uint256"
      }
    ],
    "name": "PerfFeeRateChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [],
    "name": "PerfFeeSplitChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "securityModule",
        "type": "address"
      }
    ],
    "name": "SecurityModuleSet",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "name": "oldRate",
        "type": "uint256"
      },
      {
        "indexed": false,
        "name": "newRate",
        "type": "uint256"
      }
    ],
    "name": "SmFeeRatePerSecondChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "newWatermark",
        "type": "uint256"
      }
    ],
    "name": "WatermarkReset",
    "type": "event"
  }
] as const;
