#!/usr/bin/env bash
# Regenerates src/abis/*.ts from the pinned commits in scripts/abi-sources.json (ABIs are never hand-edited).
# Requires git, jq and Foundry (forge). Output is deterministic, so CI reruns this and fails on any diff.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SOURCES="$ROOT/scripts/abi-sources.json"
CACHE="$ROOT/.cache/abi-src"
OUT="$ROOT/src/abis"

FORGE="${FORGE:-$(command -v forge || echo "$HOME/.foundry/bin/forge")}"
[ -x "$FORGE" ] || { echo "forge not found: install Foundry (https://getfoundry.sh) or set FORGE" >&2; exit 1; }

expected_foundry="$(jq -r '.foundry' "$SOURCES")"
actual_foundry="$("$FORGE" --version | sed -n 's/^forge Version: \([0-9.]*\).*/\1/p')"
if [ "$actual_foundry" != "$expected_foundry" ]; then
  echo "warning: abi-sources.json expects Foundry $expected_foundry, found $actual_foundry" >&2
fi

# Fetches exactly one commit, plus every submodule at the commit it pins, into $CACHE/<name>.
checkout() {
  local url="$1" commit="$2" dir="$3"
  if [ ! -d "$dir/.git" ]; then
    git init --quiet "$dir"
    git -C "$dir" remote add origin "$url"
  fi
  if [ "$(git -C "$dir" rev-parse -q --verify HEAD 2>/dev/null || true)" != "$commit" ]; then
    git -C "$dir" fetch --quiet --depth 1 origin "$commit"
    git -C "$dir" checkout --quiet --force "$commit"
  fi
  git -C "$dir" submodule update --quiet --init --recursive --depth 1
}

mkdir -p "$CACHE" "$OUT"
rm -f "$OUT"/*.ts

index="$OUT/index.ts"
printf '// Generated by scripts/update-abis.sh. Do not edit.\n' >"$index"

for name in $(jq -r '.repos[].name' "$SOURCES"); do
  url="$(jq -r --arg n "$name" '.repos[] | select(.name == $n) | .url' "$SOURCES")"
  commit="$(jq -r --arg n "$name" '.repos[] | select(.name == $n) | .commit' "$SOURCES")"
  echo "==> $name@$commit"
  checkout "$url" "$commit" "$CACHE/$name"

  while IFS=$'\t' read -r source contract; do
    ident="$(printf '%s' "${contract:0:1}" | tr '[:upper:]' '[:lower:]')${contract:1}Abi"
    file="$OUT/$contract.ts"
    echo "    $source -> src/abis/$contract.ts"
    abi="$(cd "$CACHE/$name" && "$FORGE" inspect "$source" abi --json | jq -S 'walk(if type == "object" then del(.internalType) else . end)')"
    {
      printf '// Generated by scripts/update-abis.sh from %s@%s\n' "$url" "$commit"
      printf '// Source: %s. Do not edit.\n' "$source"
      printf 'export const %s = %s as const;\n' "$ident" "$abi"
    } >"$file"
    printf 'export { %s } from "./%s.ts";\n' "$ident" "$contract" >>"$index"
  done < <(jq -r --arg n "$name" '.repos[] | select(.name == $n) | .contracts[] | [.source, .name] | @tsv' "$SOURCES")
done

echo "Wrote $(find "$OUT" -name '*.ts' | wc -l | tr -d ' ') files to src/abis"
